### choose freight
POST https://www.logitycoon.com/eu1/ajax/trip_accept.php
Content-Type: application/x-www-form-urlencoded
Cookie: {{cookie}}

freight[]=350991354


### tire switch
POST https://www.logitycoon.com/eu1/ajax/garage_tireswitchall.php
Content-Type: application/json
Cookie: {{cookie}}

{
  "wintertires": "1"
}


### freight autoall
GET https://www.logitycoon.com/eu1/ajax/freight_autoall?n=27519645


### freight autotrailer
GET https://www.logitycoon.com/eu1/ajax/freight_autotrailer.php?n=27519645&token=465104375
Cookie: {{cookie}}


###
GET https://www.logitycoon.com/eu1/index.php?a=freight&n=27519645
Cookie: {{cookie}}


###
GET https://www.logitycoon.com/eu1/ajax/freight_unloading.php?f=28181436&token=450018455
Cookie: {{cookie}}

###
GET https://www.logitycoon.com/eu1/ajax/freight_finish.php?f=28029177
Cookie: {{cookie}}


###
POST https://www.logitycoon.com/eu1/index.php?a=stealfuel
Cookie: {{cookie}}
content-type: application/x-www-form-urlencoded

truck=701748
